# Generated by Django 5.1.1 on 2024-10-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_livro_autor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livro",
            old_name="autor",
            new_name="autores",
        ),
    ]
