# Generated by Django 5.1.3 on 2024-11-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_itenscompra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Carrinho"), (2, "Realizado"), (3, "Pago"), (4, "Entegue")], default=1
            ),
        ),
    ]
