# Generated by Django 5.1.3 on 2024-12-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_compra_tipo_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Carrinho"), (2, "Realizado"), (3, "Pago"), (4, "Entregue")], default=1
            ),
        ),
    ]
