# Generated by Django 5.1.3 on 2025-02-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_compra_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comentario", models.CharField(max_length=100)),
            ],
        ),
    ]
