# Generated by Django 5.1.3 on 2025-02-06 13:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="data",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comentario",
            name="livro",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="livro", to="core.livro"
            ),
        ),
        migrations.AddField(
            model_name="comentario",
            name="nomeUsuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nomeUsuario",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comentario",
            name="comentario",
            field=models.TextField(max_length=1000),
        ),
    ]
