# Generated by Django 5.1.3 on 2025-02-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_comentario_data_comentario_livro_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comentario",
            old_name="nomeUsuario",
            new_name="usuario",
        ),
    ]
