# Generated by Django 5.1.3 on 2025-02-06 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_rename_nomeusuario_comentario_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="usuario", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
