# Generated by Django 5.1.3 on 2025-02-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_comentario_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="nota",
            field=models.IntegerField(
                choices=[(5, "Excelente"), (4, "Bom"), (3, "Regular"), (2, "Ruim"), (1, "Pessimo")], default=3
            ),
        ),
    ]
